version: '3.8'

services:

  srv:
    image: ${DOCKER_USERNAME}/server:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./server/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
    hostname: srv
    depends_on:
      - db
    ports:
      - "1540-1541:1540-1541"
      - "1550:1550" # для режима отладки
      - "1560-1591:1560-1591"
    entrypoint: ["/opt/1C/v8.3/x86_64/ragent", "-debug", "-http"] # entrypoint только для отладки, иначе - удалить
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  db:
    image: strizhhh/postgresql-pro-1c:9.6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - back_net

  web:
    image: ${DOCKER_USERNAME}/ws:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./ws/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
    depends_on:
      - srv
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir client -dir /var/www/client -descriptor /tmp/web/client/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;'
      && /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir api -dir /var/www/api -descriptor /tmp/web/api/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;usr=site;pwd=12345'
      && chown -R usr1cv8:grp1cv8 /var/www/client /var/www/api
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - "80:80"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./web:/tmp/web
    networks:
      - back_net
    
  client:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./client/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
      target: client-vnc
    ports:
      - "5900:5900"
    volumes:
      - client_data:/home/usr1cv8/.1cv8
      - ./tools/ibases.v8i:/home/usr1cv8/.1C/1cestart/ibases.v8i
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  receiver-init:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./client/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
      target: client-vnc
    command: >
      bash -c "/opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE File=/home/usr1cv8/db /UseTemplate /home/usr1cv8/db.dt /DumpResult /home/usr1cv8/create.log
      && chown -R usr1cv8:grp1cv8 /home/usr1cv8/db"
    volumes:
      - receiver_db:/home/usr1cv8/db
      - ./test/receiver/db.dt:/home/usr1cv8/db.dt
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  receiver-client:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./client/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
      target: client-vnc
    depends_on:
      - receiver-init
    ports:
      - "5901:5900"
    volumes:
      - receiver_data:/home/usr1cv8/.1cv8
      - receiver_db:/home/usr1cv8/db
      - ./test/receiver/ibases.v8i:/home/usr1cv8/.1C/1cestart/ibases.v8i
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  receiver-web:
    image: ${DOCKER_USERNAME}/ws:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./ws/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
    depends_on:
      - receiver-client
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir receiver -dir /var/www/receiver -descriptor /tmp/default.vrd -connstr 'File=/home/usr1cv8/db;usr=gitlab;pwd=gitlab'
      && chown -R usr1cv8:grp1cv8 /var/www/receiver
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - "8081:80"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - receiver_db:/home/usr1cv8/db
      - ./test/receiver/web:/tmp
    networks:
      - back_net

  receiver-init-2:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./client/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
      target: client-vnc
    command: >
      bash -c "/opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE File=/home/usr1cv8/db /UseTemplate /home/usr1cv8/db.dt /DumpResult /home/usr1cv8/create.log
      && chown -R usr1cv8:grp1cv8 /home/usr1cv8/db"
    volumes:
      - receiver_db_2:/home/usr1cv8/db
      - ./test/receiver/db.dt:/home/usr1cv8/db.dt
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  receiver-client-2:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./client/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
      target: client-vnc
    depends_on:
      - receiver-init-2
    ports:
      - "5902:5900"
    volumes:
      - receiver_data_2:/home/usr1cv8/.1cv8
      - receiver_db_2:/home/usr1cv8/db
      - ./test/receiver/ibases.v8i:/home/usr1cv8/.1C/1cestart/ibases.v8i
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  receiver-web-2:
    image: ${DOCKER_USERNAME}/ws:${ONEC_VERSION}
    build:
      context: https://github.com/astrizhachuk/onec-docker.git
      dockerfile: ./ws/Dockerfile
      args:
        - ONEC_USERNAME
        - ONEC_PASSWORD
        - ONEC_VERSION
    depends_on:
      - receiver-client-2
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir receiver -dir /var/www/receiver -descriptor /tmp/default.vrd -connstr 'File=/home/usr1cv8/db;usr=gitlab;pwd=gitlab'
      && chown -R usr1cv8:grp1cv8 /var/www/receiver
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - "8082:80"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - receiver_db_2:/home/usr1cv8/db
      - ./test/receiver/web:/tmp
    networks:
      - back_net

volumes:
  srv_data:
  srv_log:
  db_data:
  client_data:
  receiver_db:
  receiver_data:
  receiver_db_2:
  receiver_data_2:

networks:
  back_net: