version: '3.8'

services:

  srv:
    image: ${DOCKER_USERNAME}/server:${ONEC_VERSION}
    hostname: srv
    depends_on:
      - db
    ports:
      - "1540-1541:1540-1541"
      - "1550:1550" # для режима отладки
      - "1560-1591:1560-1591"
    # entrypoint нужен только для запуска сервера с отладкой
    entrypoint: ["/opt/1C/v8.3/x86_64/ragent", "-debug", "-http"]
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
#      - ./tools/conf.cfg:/opt/1C/v8.3/x86_64/conf/conf.cfg
    networks:
      - back_net

  db:
    image: strizhhh/postgresql-pro-1c:9.6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - back_net

  web:
    image: ${DOCKER_USERNAME}/ws:${ONEC_VERSION}
    #domainname: host.docker.internal
    depends_on:
      - srv
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir client -dir /var/www/client -descriptor /tmp/web/client/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;'
      && /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir api -dir /var/www/api -descriptor /tmp/web/api/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;usr=site;pwd=12345'
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - "80:80"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./web:/tmp/web
    networks:
      - back_net

  # ras:
  #   image: ${DOCKER_USERNAME}/server:${ONEC_VERSION}
  #   depends_on:
  #     - srv
  #   entrypoint: /opt/1C/v8.3/x86_64/ras
  #   command: "cluster srv:1540"
  #   ports:
  #     - "1545:1545"
  #   volumes:
  #     - srv_data:/home/usr1cv8/.1cv8
  #     - srv_log:/var/log/1C
  #   networks:
  #     - back_net
    
  # client:
  #   image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
  #   ports:
  #     - "5900:5900"
  #   volumes:
  #     - client_data:/home/usr1cv8/.1cv8
  #     - ./tools/ibases.v8i:/home/usr1cv8/.1C/1cestart/ibases.v8i
  #     - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
  #   networks:
  #     - back_net

  client-va:
    image: ${DOCKER_USERNAME}/client-vnc-vas:${ONEC_VERSION}
    ports:
      - "5901:5900"
    environment: 
      - ONEC_EXEC_PARAMS=ENTERPRISE /s srv\gitlabServices16 /N Администратор /Execute /usr/lib/vanessa-automation-single.epf /C"StartFeaturePlayer;workspaceRoot=/home/usr1cv8/project;VBParams=/home/usr1cv8/VAParams.json"
    volumes:
      - client_data:/home/usr1cv8/.1cv8
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
      - ./tools/VAParams.json:/home/usr1cv8/VAParams.json
      - ./:/home/usr1cv8/project
    networks:
      - back_net

  # client-va-debug:
  #   image: ${DOCKER_USERNAME}/client-vnc-va:${ONEC_VERSION}
  #   ports:
  #     - "5902:5900"
  #   environment: 
  #     #- ONEC_EXEC_PARAMS=ENTERPRISE /s srv\gitlabServices16 /N Администратор /Execute /opt/vanessa-automation/vanessa-automation.epf
  #     - ONEC_EXEC_PARAMS=DESIGNER /s srv\gitlabServices16 /N Администратор
  #   volumes:
  #     - client_data:/home/usr1cv8/.1cv8
  #     - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
  #   networks:
  #     - back_net

volumes:
  srv_data:
  srv_log:
  db_data:
  client_data:

networks:
  back_net: