version: '3.8'

services:

  srv:
    image: ${DOCKER_USERNAME}/server:${ONEC_VERSION}
    hostname: srv
    depends_on:
      - db
    ports:
      - "1540-1541:1540-1541"
      - "1550:1550" # для режима отладки
      - "1560-1591:1560-1591"
    # entrypoint нужен только для запуска сервера с отладкой
    entrypoint: ["/opt/1C/v8.3/x86_64/ragent", "-debug", "-http"]
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
    networks:
      - back_net

  db:
    image: strizhhh/postgresql-pro-1c:9.6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - back_net

  web:
    image: ${DOCKER_USERNAME}/ws:${ONEC_VERSION}
    #domainname: host.docker.internal
    depends_on:
      - srv
    command: >
      bash -c "/opt/1C/v8.3/x86_64/webinst -apache24 -wsdir client -dir /var/www/client -descriptor /tmp/web/client/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;'
      && /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir api -dir /var/www/api -descriptor /tmp/web/api/default.vrd -connstr 'Srvr=srv;Ref=gitlabServices;usr=site;pwd=12345'
      && /usr/sbin/apache2ctl -DFOREGROUND"
    ports:
      - "80:80"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
      - ./web:/tmp/web
    networks:
      - back_net

  client:
    image: ${DOCKER_USERNAME}/client-vnc:${ONEC_VERSION}
    ports:
      - "5900:5900"
    volumes:
      - client_data:/home/usr1cv8/.1cv8
      - client_data:/home/usr1cv8/.1C
      - ./tools/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
    networks:
      - back_net

volumes:
  srv_data:
  srv_log:
  db_data:
  client_data:

networks:
  back_net: